version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    environment:
      - ACTIVEMQ_NAME=activemq
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
    ports:
      - "61616:61616"
      - "8161:8161"