-- Table: public.curs_data

-- DROP TABLE IF EXISTS public.curs_data;

CREATE TABLE IF NOT EXISTS public.curs_data
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    currency character varying(3) COLLATE pg_catalog."default",
    code numeric(3,0),
    curs numeric(5,2),
    curs_date date,
    CONSTRAINT curs_data_pkey PRIMARY KEY (id)
)