-- Table: public.curs_data

-- DROP TABLE IF EXISTS public.curs_data;

CREATE TABLE IF NOT EXISTS public.curs_request
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    curs_date date,
    request_date timestamp without time zone,
    correlation_id character varying(40) COLLATE pg_catalog."default",
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT curs_request_pkey PRIMARY KEY (correlation_id)
)
